# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
dist: xenial
latex: false
# Change to false when developing; true since CRAN will complain about WARNINGS
warnings_are_errors: true

jobs:
  include:
  - os: osx  # check package on macOS 10.13 (all other checks are on linux)
  - r: devel # check package for development version of R
  - r: release # Check package for current release and deploy to ghpages
    after_success:
    - R CMD INSTALL . # Install package and build site
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'pkgdown::build_site()'
    # Deploy to github pages
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: false
      local-dir: docs
      on:
        branch: master
